eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
 datasource:
    ##url: jdbc:mysql://localhost:3306/likki_bank_sol?useSSL=false
    url: jdbc:sqlserver://likkibanksoldbserver.database.windows.net;databaseName=likki_bank_sol
    username: likkibanksol
    password: Password@123
   
 mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
 
 application:
    name: LikkiBankSolutions
server:
 port: 8081